### ISSUE TITLE
Spec detection bug

### ISSUE THREAD

**Issue by Schaka** [miraage/gladdy#2]
Currently there is a bug where units get the wrong spec (the spec the unit at the same position had in the previous arena match). I have not been able to reproduce it, but I think it might be caused by you or your opponents leaving the arena (maybe during combat?).

For example: The bug occurs, you play against shadowpriest and rogue, shadowpriest is arena1 and rogue is arena2. The next game you play against shaman and warrior. Shaman is arena1 and warrior is arena2. 
Now Gladdy will show enemies as Shadow Shaman and Subtetly Warrior. The next game you face the other team again and now you're against Arms Priest and Restoration Rogue.
I have tried to fix this, specifically for my cooldown tracker but haven't been able to find the bug.

**Comment by miraage** [comment]
I have no windows/wow currently. Could you please check by adding debug prints after [reset](https://github.com/miraage/gladdy/blob/master/Gladdy.lua#L308)?
Sounds strange because reset is applied every time u are leaving arena and [spec described](https://github.com/miraage/gladdy/blob/master/Frame.lua#L21) as empty string.

**Comment by Schaka** [comment]
Like I said, I haven't been able to reproduce it and the code looks fine. I need to figure out when exactly it happen. I'll add more prints to debug it and see where that takes me while playing.

**Comment by Schaka** [comment]
This was fixed in the process of migrating Gladdy. I am no maintaining a fork of it and have added a bunch of features, including TrinketTracker. I also fixed DR timers, although they definitely need more work, which I will take care of soon™
