### ISSUE TITLE
Enemies "greying out"

### ISSUE THREAD

**Issue by Schaka** [miraage/gladdy#3]
Is it possible to assign the button status to a unit, before it gets assigned a GUID and then assign it a GUID later?  It would prevent the greying out bug, that currently makes keybinding on some servers really annoying.

I have written an addon called ArenaIdentify, that tries to find your enemies and sync them to Gladdy before the arena starts, but it's not always succesful.
Sorry for the public issues, can't reach you elsewhere.

**Comment by Schaka** [comment]
I found that there is either a server side solution (I developed it here) https://github.com/Looking4Group/L4G_Core/pull/75 or use a Lua unlocker like wRobot, EWT, etc to circumvent this. 

My fork of Gladdy also has this mostly solved by auto-picking up enemies.

**Comment by miraage** [comment]
Hey @Schaka . I quit WoW a few years ago. I can either give you full collaborator permissions on this repository or I can update README in this repo to point on your fork so people won't be confused.
What do you think?

**Comment by Schaka** [comment]
If you wanted to link to my fork that in the readme, that'd be great.
